"""
Terraform Configuration Generator
Generates .tfvars files based on demo scenario and configuration
"""

from typing import Dict, Optional
from pathlib import Path
from pydantic import BaseModel, Field
from src.ai.scenario_generator import DemoScenario


class TerraformConfig(BaseModel):
    """Configuration for Terraform dbt Cloud setup"""
    
    # dbt Cloud
    dbt_cloud_account_id: str
    dbt_cloud_token: str
    dbt_cloud_host_url: str = "https://cloud.getdbt.com/api"
    
    # Project
    project_name: str
    project_description: str = ""
    
    # Repository
    github_repo_url: str
    github_installation_id: str
    
    # Snowflake
    snowflake_account: str
    snowflake_database: str
    snowflake_warehouse: str
    snowflake_role: str
    snowflake_user: str
    snowflake_password: str
    snowflake_schema: str = "analytics"
    
    # Environment
    dev_threads: int = 4
    prod_threads: int = 8
    
    # Jobs
    enable_production_job: bool = True
    production_job_schedule_cron: str = "0 6 * * *"
    
    # Semantic Layer
    enable_semantic_layer: bool = False


def generate_terraform_config(
    scenario: DemoScenario,
    github_repo_url: str,
    dbt_cloud_account_id: str,
    dbt_cloud_token: str,
    github_installation_id: str,
    snowflake_account: str,
    snowflake_database: str,
    snowflake_warehouse: str,
    snowflake_role: str,
    snowflake_user: str,
    snowflake_password: str,
    snowflake_schema: str = "analytics",
    dbt_cloud_host_url: str = "https://cloud.getdbt.com/api",
    **kwargs
) -> TerraformConfig:
    """
    Generate Terraform configuration from demo scenario
    
    Args:
        scenario: Demo scenario
        github_repo_url: GitHub repository URL
        dbt_cloud_account_id: dbt Cloud account ID
        dbt_cloud_token: dbt Cloud API token
        github_installation_id: GitHub App installation ID
        snowflake_account: Snowflake account identifier
        snowflake_database: Snowflake database name
        snowflake_warehouse: Snowflake warehouse name
        snowflake_role: Snowflake role
        snowflake_user: Snowflake user
        snowflake_password: Snowflake password
        snowflake_schema: Snowflake schema (default: analytics)
        dbt_cloud_host_url: dbt Cloud API URL
        **kwargs: Additional configuration options
    
    Returns:
        TerraformConfig object
    """
    
    # Generate project name from scenario
    project_name = f"{scenario.company_name} Demo"
    project_description = (
        f"dbt Cloud demo project for {scenario.company_name} ({scenario.industry})"
    )
    
    return TerraformConfig(
        dbt_cloud_account_id=dbt_cloud_account_id,
        dbt_cloud_token=dbt_cloud_token,
        dbt_cloud_host_url=dbt_cloud_host_url,
        project_name=project_name,
        project_description=project_description,
        github_repo_url=github_repo_url,
        github_installation_id=github_installation_id,
        snowflake_account=snowflake_account,
        snowflake_database=snowflake_database,
        snowflake_warehouse=snowflake_warehouse,
        snowflake_role=snowflake_role,
        snowflake_user=snowflake_user,
        snowflake_password=snowflake_password,
        snowflake_schema=snowflake_schema,
        enable_semantic_layer=scenario.include_semantic_layer,
        **kwargs
    )


def generate_tfvars_content(config: TerraformConfig) -> str:
    """
    Generate terraform.tfvars file content
    
    Args:
        config: Terraform configuration
    
    Returns:
        String content for terraform.tfvars file
    """
    
    # Escape quotes in token and other string values for Terraform
    def escape_terraform_string(value: str) -> str:
        """Escape special characters for Terraform string literals"""
        if value is None:
            return ""
        return str(value).replace('"', '\\"').replace('\\', '\\\\')
    
    content = f'''# Auto-generated Terraform variables
# Generated by dbt Demo Automation Tool

# dbt Cloud Configuration
dbt_cloud_account_id = "{escape_terraform_string(config.dbt_cloud_account_id)}"
dbt_cloud_token      = "{escape_terraform_string(config.dbt_cloud_token)}"
dbt_cloud_host_url   = "{escape_terraform_string(config.dbt_cloud_host_url)}"

# Project Configuration
project_name        = "{config.project_name}"
project_description = "{config.project_description}"

# Repository Configuration
github_repo_url        = "{config.github_repo_url}"
github_installation_id = "{config.github_installation_id}"

# Snowflake Configuration
snowflake_account   = "{config.snowflake_account}"
snowflake_database  = "{config.snowflake_database}"
snowflake_warehouse = "{config.snowflake_warehouse}"
snowflake_role      = "{config.snowflake_role}"
snowflake_user      = "{config.snowflake_user}"
snowflake_password  = "{config.snowflake_password}"
snowflake_schema    = "{config.snowflake_schema}"

# Environment Configuration
dev_threads  = {config.dev_threads}
prod_threads = {config.prod_threads}

# Job Configuration
enable_production_job        = {str(config.enable_production_job).lower()}
production_job_schedule_cron = "{config.production_job_schedule_cron}"

# Semantic Layer
enable_semantic_layer = {str(config.enable_semantic_layer).lower()}
'''
    
    return content


def write_terraform_files(
    config: TerraformConfig,
    output_dir: Path
) -> Dict[str, Path]:
    """
    Write Terraform configuration files to directory
    
    Args:
        config: Terraform configuration
        output_dir: Directory to write files to
    
    Returns:
        Dictionary mapping file types to paths
    """
    
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate terraform.tfvars
    tfvars_content = generate_tfvars_content(config)
    tfvars_path = output_dir / "terraform.tfvars"
    
    with open(tfvars_path, 'w') as f:
        f.write(tfvars_content)
    
    return {
        'tfvars': tfvars_path
    }





